site_name: AWS Technical Essentials
site_description: Manual de estudio en español del curso AWS Technical Essentials
site_author: José Antonio Seguido Doblado
site_url: https://seguidodoblado.github.io/aws-technical-essentials/
repo_name: GitHub
repo_url: https://github.com/seguidodoblado/aws-technical-essentials

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.top
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: slate
      primary: black
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro
    - scheme: default
      primary: black
      accent: orange
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro

nav:
  - Inicio: index.md

  - Guía del estudiante:
      - 00. Visión general del curso:
          - Visión general: guia-del-estudiante/00-Vision-general-del-curso/00-0-vision-general.md
          - Mapa del curso: guia-del-estudiante/00-Vision-general-del-curso/00-1-mapa.md
          - Resumen de módulos: guia-del-estudiante/00-Vision-general-del-curso/00-2-resumen-modulos.md
      - 01. Introducción a Amazon Web Services:
          - Objetivos: guia-del-estudiante/01-Introduccion-a-amazon-web-services/01-0-objetivos.md
          - ¿Qué es la computación en la nube?: guia-del-estudiante/01-Introduccion-a-amazon-web-services/01-1-computacion-nube.md
          - Infraestructura global de AWS: guia-del-estudiante/01-Introduccion-a-amazon-web-services/01-2-infraestructura-global.md
          - Gestión de los servicios de AWS: guia-del-estudiante/01-Introduccion-a-amazon-web-services/01-3-gestion-servicios.md
          - Modelo de responsabilidad compartida: guia-del-estudiante/01-Introduccion-a-amazon-web-services/01-4-responsabilidad-compartida.md
          - AWS Identity and Access Management (IAM): guia-del-estudiante/01-Introduccion-a-amazon-web-services/01-5-iam.md
      - 02. Servicios de computación en la nube:
          - Objetivos: guia-del-estudiante/02-Servicios-de-computacion-en-la-nube/02-0-objetivos.md
          - Computación como servicio en AWS: guia-del-estudiante/02-Servicios-de-computacion-en-la-nube/02-1-computacion-servicio.md
          - Amazon Elastic Compute Cloud (Amazon EC2): guia-del-estudiante/02-Servicios-de-computacion-en-la-nube/02-2-amazon-ec2.md
          - Ciclo de vida de una instancia de Amazon EC2: guia-del-estudiante/02-Servicios-de-computacion-en-la-nube/02-3-ciclo-vida-ec2.md
          - Familias de instancias de Amazon EC2: guia-del-estudiante/02-Servicios-de-computacion-en-la-nube/02-4-familias-ec2.md
          - Servicios de contenedores de AWS: guia-del-estudiante/02-Servicios-de-computacion-en-la-nube/02-5-contenedores.md
          - Computación sin servidor (Serverless): guia-del-estudiante/02-Servicios-de-computacion-en-la-nube/02-6-serverless.md
      - 03. Servicios de redes de AWS:
          - Objetivos: guia-del-estudiante/03-Servicios-de-redes-de-aws/03-0-objetivos.md
          - Amazon Virtual Private Cloud (Amazon VPC): guia-del-estudiante/03-Servicios-de-redes-de-aws/03-1-amazon-vpc.md
          - Classless Inter-Domain Routing (CIDR): guia-del-estudiante/03-Servicios-de-redes-de-aws/03-2-cidr.md
          - Acceso desde Internet y redes remotas: guia-del-estudiante/03-Servicios-de-redes-de-aws/03-3-acceso-internet-redes-remotas.md
          - Network Access Control Lists (NACLs): guia-del-estudiante/03-Servicios-de-redes-de-aws/03-4-nacl.md
          - Security Groups: guia-del-estudiante/03-Servicios-de-redes-de-aws/03-5-security-groups.md
          - Seguridad en múltiples capas: guia-del-estudiante/03-Servicios-de-redes-de-aws/03-6-seguridad-multiples-capas.md
      - 04. Servicios de almacenamiento de AWS:
          - Objetivos: guia-del-estudiante/04-Servicios-de-almacenamiento-de-aws/04-0-objetivos.md
          - Tipos de almacenamiento: guia-del-estudiante/04-Servicios-de-almacenamiento-de-aws/04-1-tipos-almacenamiento.md
          - Almacenamiento en bloques: guia-del-estudiante/04-Servicios-de-almacenamiento-de-aws/04-2-almacenamiento-bloques.md
          - Almacenamiento de archivos: guia-del-estudiante/04-Servicios-de-almacenamiento-de-aws/04-3-almacenamiento-archivos.md
          - Almacenamiento de objetos: guia-del-estudiante/04-Servicios-de-almacenamiento-de-aws/04-4-almacenamiento-objetos.md
          - Clases de almacenamiento de Amazon S3: guia-del-estudiante/04-Servicios-de-almacenamiento-de-aws/04-5-clases-amazon-s3.md
      - 05. Servicios de base de datos de AWS:
          - Objetivos: guia-del-estudiante/05-Servicios-de-base-de-datos-de-aws/05-0-objetivos.md
          - Beneficios de las bases de datos en AWS: guia-del-estudiante/05-Servicios-de-base-de-datos-de-aws/05-1-beneficios-bases-datos.md
          - Tipos de bases de datos: guia-del-estudiante/05-Servicios-de-base-de-datos-de-aws/05-2-tipos-bases-datos.md
          - Bases de datos relacionales: guia-del-estudiante/05-Servicios-de-base-de-datos-de-aws/05-3-bases-datos-relacionales.md
          - Bases de datos administradas: guia-del-estudiante/05-Servicios-de-base-de-datos-de-aws/05-4-bases-datos-administradas.md
          - Amazon Relational Database Service (Amazon RDS): guia-del-estudiante/05-Servicios-de-base-de-datos-de-aws/05-5-amazon-rds.md
          - Amazon DynamoDB: guia-del-estudiante/05-Servicios-de-base-de-datos-de-aws/05-6-amazon-dynamodb.md
          - Características de Amazon DynamoDB: guia-del-estudiante/05-Servicios-de-base-de-datos-de-aws/05-7-caracteristicas-dynamodb.md
      - 06. Monitorización, equilibrio de carga y escalado:
          - Objetivos: guia-del-estudiante/06-Monitorizacion-equilibrio-de-carga-y-escalado/06-0-objetivos.md
          - Monitorización: guia-del-estudiante/06-Monitorizacion-equilibrio-de-carga-y-escalado/06-1-monitorizacion.md
          - Escalado: guia-del-estudiante/06-Monitorizacion-equilibrio-de-carga-y-escalado/06-2-escalado.md
          - Equilibrio de carga: guia-del-estudiante/06-Monitorizacion-equilibrio-de-carga-y-escalado/06-3-equilibrio-carga.md
      - 07. Resumen del curso:
          - Arquitectura de la aplicación Final Employee Directory: guia-del-estudiante/07-Resumen-del-curso/07-1-arquitectura-employee-directory.md
          - Arquitectura Serverless Employee Directory: guia-del-estudiante/07-Resumen-del-curso/07-2-arquitectura-serverless-employee-directory.md

  - Laboratorios:
      - General:
          - Contenidos: laboratorios/00-general/00-0-contenidos.md
      - Introducción a AWS IAM:
          - Introducción: laboratorios/01-introduccion-a-aws-iam/01-0-introduccion.md
          - Objetivos: laboratorios/01-introduccion-a-aws-iam/01-1-objetivos.md